repos:
  - repo: local
    hooks:
      - id: rlx-llm-guard
        name: RLx LLM Guard
        entry: python3 scripts/llm_guard.py --root .
        language: system
        pass_filenames: false
      - id: rlx-net-guard
        name: RLx Net Guard
        entry: python3 scripts/net_guard.py --root .
        language: system
        pass_filenames: false
      - id: rlx-secrets-guard
        name: RLx Secrets Guard
        entry: python3 scripts/secrets_guard.py --root .
        language: system
        pass_filenames: false
      - id: rlx-purity
        name: RLx Purity Check
        entry: python3 scripts/purity_check.py --root .
        language: system
        pass_filenames: false