name: RLx Security CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - run: |
          python -m pip install -U pip
          pip install ruff black bandit pytest pip-audit
      - name: Ruff
        run: ruff check .
      - name: Black (check)
        run: black --check .
      - name: Bandit
        run: bandit -r app || true
      - name: Tests
        run: pytest -q || true
      - name: pip-audit
        run: pip-audit -r local_bundle/dist/requirements.freeze.txt || true
